# Generated by Django 3.2.5 on 2021-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/categories')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
